// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Lg5TgSoKIa3cmB0k4DyyGI5P4lS6vv0',
    appId: '1:236798175416:web:03a9dea9c2bc219b656c4d',
    messagingSenderId: '236798175416',
    projectId: 'proje-75175',
    authDomain: 'proje-75175.firebaseapp.com',
    storageBucket: 'proje-75175.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcp3JG_svH3eRb6tFpTnQc_eq3S56p_sg',
    appId: '1:236798175416:android:efdc02cad18357c2656c4d',
    messagingSenderId: '236798175416',
    projectId: 'proje-75175',
    storageBucket: 'proje-75175.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvyrsrB3JRGwWlqaalMM6f9dBAcpthPVc',
    appId: '1:236798175416:ios:2c4302dbf2fa8482656c4d',
    messagingSenderId: '236798175416',
    projectId: 'proje-75175',
    storageBucket: 'proje-75175.appspot.com',
    iosClientId: '236798175416-0unsur7gbmjbcho4910vffvs1e9pght2.apps.googleusercontent.com',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvyrsrB3JRGwWlqaalMM6f9dBAcpthPVc',
    appId: '1:236798175416:ios:2c4302dbf2fa8482656c4d',
    messagingSenderId: '236798175416',
    projectId: 'proje-75175',
    storageBucket: 'proje-75175.appspot.com',
    iosClientId: '236798175416-0unsur7gbmjbcho4910vffvs1e9pght2.apps.googleusercontent.com',
    iosBundleId: 'com.example.proje',
  );
}
